name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Extract Release Notes
        id: release_notes
        run: |
          content=$(awk -v tag="${{ github.ref }}" '/## \['tag'\]/{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)
          content="${content//$'\n'/'%0A'}"
          content="${content//$'`'/'\`'}"
          echo "::set-output name=body::$content"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROIDDEVNOTESX_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release_notes.outputs.body }}
          draft: false
          prerelease: false

      - name: Upload AAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROIDDEVNOTESX_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./library/build/outputs/aar/library-release.aar
          asset_name: library-release.aar
          asset_content_type: application/zip
